name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    tags:
      - 'v*'  # Triggers on tags like v1.0.0
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Extract image tag
      id: vars
      run: |
        if [[ "${{ github.ref_type }}" == "tag" ]]; then
          TAG=${GITHUB_REF##*/}
        else
          TAG=${GITHUB_SHA::7}
        fi
        echo "tag=$TAG" >> $GITHUB_OUTPUT

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        file: Dockerfile.varafm
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/varafm:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/varafm:${{ steps.vars.outputs.tag }}
